import React, { useRef, useState } from 'react';
import { motion } from 'framer-motion';
import SlideCard from './SlideCard';
import { ArrowLeft, ArrowRight, RefreshCcw, LayoutGrid, Tablet, Monitor } from 'lucide-react';

const CarouselDisplay = ({ slides, onUpdate, onRegenerate }) => {
  const scrollRef = useRef(null);
  const [viewMode, setViewMode] = useState('carousel');

  const scroll = (direction) => {
    if (scrollRef.current) {
      const { scrollLeft, clientWidth } = scrollRef.current;
      const scrollTo = direction === 'left' 
        ? scrollLeft - clientWidth
        : scrollLeft + clientWidth;
      
      scrollRef.current.scrollTo({ left: scrollTo, behavior: 'smooth' });
    }
  };

  return (
    <div className="w-full max-w-[1400px] mx-auto px-4 md:px-8 pb-32">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-col md:flex-row justify-between items-start md:items-end mb-12 gap-6"
      >
        <div>
          <h2 className="text-4xl font-extrabold text-white tracking-tighter mb-3">
            Preview Your <span className="gradient-text">Carousel</span>
          </h2>
          <p className="text-slate-400 font-medium text-lg">
            Professional storytelling slides, generated by AI.
          </p>
        </div>

        <div className="flex flex-wrap gap-4">
          <div className="flex bg-white/5 p-1 rounded-2xl border border-white/10 backdrop-blur-md">
            <button 
              onClick={() => setViewMode('carousel')}
              className={`p-3 rounded-xl transition-all ${viewMode === 'carousel' ? 'bg-indigo-500 text-white shadow-lg shadow-indigo-500/20' : 'text-slate-400 hover:text-white'}`}
              title="Carousel View"
            >
              <LayoutGrid size={20} />
            </button>
            <button 
              onClick={() => setViewMode('grid')}
              className={`p-3 rounded-xl transition-all ${viewMode === 'grid' ? 'bg-indigo-500 text-white shadow-lg shadow-indigo-500/20' : 'text-slate-400 hover:text-white'}`}
              title="Grid View"
            >
              <Tablet size={20} />
            </button>
          </div>

          <button
            onClick={onRegenerate}
            className="flex items-center gap-2 px-6 py-3 bg-white/5 border border-white/10 rounded-2xl text-slate-300 font-bold hover:bg-white/10 hover:text-white transition-all active:scale-95 group shadow-xl"
          >
            <RefreshCcw size={18} className="group-hover:rotate-180 transition-transform duration-500" />
            <span>Regenerate Content</span>
          </button>
        </div>
      </motion.div>

      <div className="relative group">
        {/* Navigation Buttons (Floating) */}
        {viewMode === 'carousel' && (
          <>
            <motion.button
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.9 }}
              onClick={() => scroll('left')}
              className="absolute -left-4 md:-left-8 top-1/2 -translate-y-1/2 z-20 p-5 glass-panel rounded-full text-white shadow-2xl border border-white/20 hover:text-indigo-400 transition-colors hidden lg:block"
            >
              <ArrowLeft size={28} strokeWidth={2.5} />
            </motion.button>
            
            <motion.button
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.9 }}
              onClick={() => scroll('right')}
              className="absolute -right-4 md:-right-8 top-1/2 -translate-y-1/2 z-20 p-5 glass-panel rounded-full text-white shadow-2xl border border-white/20 hover:text-indigo-400 transition-colors hidden lg:block"
            >
              <ArrowRight size={28} strokeWidth={2.5} />
            </motion.button>
          </>
        )}

        {/* Carousel / Grid Content */}
        <motion.div 
          layout
          ref={scrollRef}
          className={`${
            viewMode === 'carousel' 
              ? 'carousel-container flex overflow-x-auto gap-6 py-10 px-4' 
              : 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 py-10'
          }`}
        >
          {slides.map((slide, index) => (
            <motion.div
              layout
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: index * 0.1 }}
              key={index}
            >
              <SlideCard 
                index={index} 
                slide={slide} 
                onUpdate={onUpdate}
              />
            </motion.div>
          ))}
        </motion.div>
      </div>

      {/* Modern Progress Bar */}
      {viewMode === 'carousel' && (
        <div className="mt-12 flex justify-center items-center gap-3">
          {slides.map((_, index) => (
            <motion.div 
              key={index} 
              className={`h-1.5 rounded-full transition-all duration-500 ${index === 0 ? 'bg-gradient-to-r from-indigo-500 to-purple-500 w-12' : 'bg-white/10 w-4'}`}
            />
          ))}
        </div>
      )}
    </div>
  );
};

export default CarouselDisplay;
